import type { CapabilityDetailDto, CaptureDetailDto } from "@/lib/caphub/registry/queries";

export function CaptureRegistryDetail({ view }: { view: CaptureDetailDto }) {
  if (view.kind === "not_found") return <section className="registry-state"><h1>Capture not found</h1><p>The Capture ID is invalid or unavailable.</p></section>;
  return <div className="registry-detail-page"><header><span className="registry-kicker">Caphub · Capture lineage</span><h1>Trace the decision back to the source.</h1><p>Raw object keys, filesystem paths, prompts, reasoning, and secrets are withheld.</p></header><div className="registry-detail-grid"><main><section className="registry-recommendation"><h2>Immutable source preserved</h2><p>{view.capture.filename} · {view.capture.mimeType} · {view.capture.objectBytes} bytes</p><code>{view.capture.objectDigest}</code></section><section className="registry-section"><h2>Evidence and Claims</h2>{view.packet.claims.map((claim) => <article className="registry-claim" key={claim.id}><span>{claim.basis}</span><p>{claim.statement}</p><code>{claim.id}</code></article>)}</section><section className="registry-section"><h2>Safe model-call metadata</h2>{view.modelCalls.length ? view.modelCalls.map((call) => <p key={call.eventId}>{call.provider} · {call.model} · {call.stage} · {call.type}</p>) : <p>No model calls recorded.</p>}</section></main><aside className="registry-detail-aside"><h2>Lineage</h2><ol><li>Capture <code>{view.capture.id}</code></li><li>Analysis job <code>{view.job?.id ?? "not started"}</code></li><li>ReviewPacket <code>{view.packet.packetId || "not available"}</code></li></ol></aside></div></div>;
}

export function CapabilityRegistryDetail({ view }: { view: CapabilityDetailDto }) {
  if (view.kind === "not_found") return <section className="registry-state"><h1>Capability Candidate not found</h1><p>The Candidate ID is invalid or unavailable.</p></section>;
  return <div className="registry-detail-page"><header><span className="registry-kicker">Caphub · Candidate Registry</span><h1>A Candidate is not a released capability.</h1><p>Inspect the current immutable version while later-phase artifacts remain honestly absent.</p></header><div className="registry-detail-grid"><main><section className="registry-recommendation"><h2>{view.candidate.name}</h2><p>Candidate only · not available to runtime routing.</p><code>{view.candidateId}</code></section><section className="registry-section"><h2>Relationships and decision</h2><p>Review request: <code>{view.request?.id ?? "not created"}</code></p><p>Decision: {view.decision?.action ?? "waiting"}</p>{view.packet.evidence.map((item) => <p key={item.id}>{item.title} · Tier {item.tier}</p>)}</section></main><aside className="registry-detail-aside"><h2>Later-phase artifacts</h2><div className="registry-future-empty"><strong>No BuildProposal</strong><p>P3 approval cannot start an implementation handoff.</p></div><div className="registry-future-empty"><strong>No Release</strong><p>Capability Package generation belongs to P4.</p></div><div className="registry-future-empty"><strong>No Deployment or Usage</strong><p>Nothing is installed or routed.</p></div></aside></div></div>;
}
