import type { CapabilityDetailDto, CapabilityExportDto, CaptureDetailDto } from "@/lib/caphub/registry/queries";

export function CaptureRegistryDetail({ view }: { view: CaptureDetailDto }) {
  if (view.kind === "not_found") return <section className="registry-state"><h1>Capture not found</h1><p>The Capture ID is invalid or unavailable.</p></section>;
  const stateCopy = view.analysisState === "complete"
    ? "Complete imported lineage"
    : view.analysisState === "partial"
      ? "Partial analysis · ReviewPacket not available"
      : "Analysis artifact unavailable";
  return <div className="registry-detail-page"><header><span className="registry-kicker">Caphub · Capture lineage</span><h1>Trace the decision back to the source.</h1><p>Raw object keys, filesystem paths, prompts, reasoning, and secrets are withheld.</p></header><div className="registry-detail-grid"><main>
    <section className="registry-recommendation"><h2>Immutable source preserved</h2><p>{view.capture.filename} · {view.capture.mimeType} · {view.capture.objectBytes} bytes</p><p><strong>Analysis:</strong> {stateCopy}</p><code>{view.capture.objectDigest}</code></section>
    <section className="registry-section"><h2>Ordered OCR</h2>{view.packet.ocr.length ? <ol>{view.packet.ocr.map((block) => <li key={`${block.imageIndex}:${block.text}`}><strong>Image {block.imageIndex + 1}</strong> · {block.text}</li>)}</ol> : <p>No OCR output is available for this Capture.</p>}</section>
    <section className="registry-section"><h2>Entities, Claims, and source checks</h2>{view.packet.entities.length ? <ul>{view.packet.entities.map((entity) => <li key={entity.name}><strong>{entity.name}</strong>{entity.aliases.length ? ` · aliases ${entity.aliases.join(", ")}` : ""}</li>)}</ul> : <p>No extracted entities are available.</p>}{view.packet.claims.map((claim) => <article className="registry-claim" key={claim.id}><span>{claim.basis}</span><p>{claim.statement}</p><code>{claim.id} · sources {claim.evidenceIds.join(" · ")}</code></article>)}{view.packet.evidence.map((item) => <article className="registry-source-check" key={item.id}><a href={item.sourceUrl} target="_blank" rel="noreferrer noopener">{item.title}</a><p>Tier {item.tier} · checked {item.checkedAt}</p><code>{item.id} · {item.contentDigest}</code></article>)}</section>
    <section className="registry-section"><h2>Safe model-call metadata</h2>{view.modelCalls.length ? view.modelCalls.map((call) => <p key={call.eventId}>{call.provider} · {call.model} · {call.stage} · {call.type}</p>) : <p>No model calls recorded.</p>}</section>
    <section className="registry-section"><h2>Decision timeline</h2>{view.registryImport ? <p>Review <code>{view.registryImport.reviewRequestId}</code> · {view.registryImport.reviewState.replaceAll("_", " ")}</p> : <p>No Registry import is available.</p>}{view.decisions.length ? <ol>{view.decisions.map((decision) => <li key={decision.id}><strong>{decision.action}</strong> · {decision.recordedAt}<code>{decision.id}</code></li>)}</ol> : <p>No terminal decision has been recorded.</p>}</section>
  </main><aside className="registry-detail-aside"><h2>Lineage</h2><ol><li>Capture <code>{view.capture.id}</code></li><li>Analysis job <code>{view.job?.id ?? "not started"}</code></li><li>ReviewPacket v{view.packetVersion ?? "—"}<code>{view.packet.packetId || "not available"}</code>{view.packetDigest && <code>{view.packetDigest}</code>}</li><li>Registry import <code>{view.registryImport?.id ?? "not imported"}</code></li><li>Review request <code>{view.registryImport?.reviewRequestId ?? "not created"}</code></li></ol></aside></div></div>;
}

export function CapabilityRegistryDetail({ view, exportView }: { view: CapabilityDetailDto; exportView?: CapabilityExportDto }) {
  if (view.kind === "not_found") return <section className="registry-state"><h1>Capability Candidate not found</h1><p>The Candidate ID is invalid or unavailable.</p></section>;
  const ready = exportView?.kind === "ready" ? exportView : null;
  const deployed = ready ? ready.deployment.activePointer?.releaseId === ready.release.recordId : false;
  const headerCopy = deployed
    ? ["Deployed and reviewable end to end.", "Active pointer, immutable history, and the exact approvals behind them are visible below."]
    : ready
      ? ["A Release candidate binds this capability.", "Release state, adapter previews, and deployment planning stay read-only on this page."]
      : ["A Candidate is not a released capability.", "Inspect the current immutable version while later-phase artifacts remain honestly absent."];
  return <div className="registry-detail-page" data-lifecycle-state={deployed ? "deployed" : ready ? "release" : "candidate"}><header><span className="registry-kicker">Caphub · Candidate Registry</span><h1>{headerCopy[0]}</h1><p>{headerCopy[1]}</p></header><div className="registry-detail-grid"><main><section className="registry-recommendation"><h2>{view.candidate.name}</h2><p>{ready ? "Release-bound" : "Candidate only"} · current immutable version {view.currentVersion} · not available to runtime routing.</p>{view.staleVersion && <p role="alert"><strong>Stale version warning:</strong> this review binds v{view.request?.subjectVersion}, not current v{view.currentVersion}.</p>}<code>{view.candidateId}</code></section><section className="registry-section"><h2>Versions and relationships</h2>{view.versions.map((version) => <p key={version.version}>Version {version.version} · {version.createdAt}<code>{version.digest}</code></p>)}{view.lineage.length ? <ol>{view.lineage.map((edge, index) => <li key={`${edge.fromId}:${edge.relationship}:${edge.toId}:${index}`}><code>{edge.fromKind} v{edge.fromVersion}</code> {edge.relationship} <code>{edge.toKind} v{edge.toVersion}</code></li>)}</ol> : <p>No relationships recorded.</p>}</section><section className="registry-section"><h2>Decision timeline</h2><p>Review request: <code>{view.request?.id ?? "not created"}</code></p>{view.decisions.length ? <ol>{view.decisions.map((decision) => <li key={decision.id}><strong>{decision.action}</strong> · {decision.recordedAt}<code>{decision.id}</code></li>)}</ol> : <p>Decision: waiting</p>}{view.packet.evidence.map((item) => <p key={item.id}>{item.title} · Tier {item.tier}</p>)}</section></main><aside className="registry-detail-aside"><h2>Later-phase artifacts</h2><div className="registry-future-empty"><strong>No BuildProposal</strong><p>P3 approval cannot start an implementation handoff.</p></div>{ready ? <div className="registry-future-empty" data-lifecycle-card="release"><strong>{ready.release.slug} · v{ready.release.semver}</strong><p>Release {ready.release.state.replaceAll("_", " ")} · Registry version {ready.release.version}.</p></div> : <div className="registry-future-empty"><strong>No Release</strong><p>Capability Package generation belongs to P4.</p></div>}{deployed && ready ? <div className="registry-future-empty" data-lifecycle-card="deployment"><strong>Active deployment</strong><p>{ready.deployment.history.length} deployment record{ready.deployment.history.length === 1 ? "" : "s"} · pointer <code>{ready.deployment.activePointer?.deploymentId ?? "unavailable"}</code></p></div> : ready ? <div className="registry-future-empty" data-lifecycle-card="deployment"><strong>No deployment recorded yet</strong><p>Planning and approval stay gated outside the browser.</p></div> : <div className="registry-future-empty"><strong>No Deployment or Usage</strong><p>Nothing is installed or routed.</p></div>}</aside></div></div>;
}
